"""Chapter model."""

from __future__ import annotations

import builtins  # noqa: TC003
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, ForeignKey, Index, Integer, String, func, select
from sqlalchemy.orm import Mapped, mapped_column, relationship

from oeapp.db import Base
from oeapp.models.mixins import SaveDeleteMixin

if TYPE_CHECKING:
    from collections.abc import Sequence

    from oeapp.models.project import Project
    from oeapp.models.section import Section


class Chapter(SaveDeleteMixin, Base):
    """
    Represents a chapter within a project.
    """

    #: Tablename  .
    __tablename__ = "chapters"
    #: Table args  .
    __table_args__ = (
        Index("idx_chapters_project_number", "project_id", "number"),
    )

    #: The chapter ID.
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    #: The project ID.
    project_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    #: The chapter number (1-based).
    number: Mapped[int] = mapped_column(Integer, nullable=False)
    #: The chapter title.
    title: Mapped[str | None] = mapped_column(String, nullable=True)
    #: Whether chapter title was auto-generated by ingest logic.
    title_auto: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    #: Relationships
    project: Mapped[Project] = relationship("Project", back_populates="chapters")
    #: Sections.
    sections: Mapped[builtins.list[Section]] = relationship(
        "Section",
        back_populates="chapter",
        cascade="all, delete-orphan",
        order_by="Section.number",
    )

    @classmethod
    def get(cls, chapter_id: int) -> Chapter | None:
        """
        Get a chapter by ID.

        Args:
            chapter_id: The chapter ID

        Returns:
            The chapter or None if not found

        """
        session = cls._get_session()
        return session.get(cls, chapter_id)

    @classmethod
    def create(  # noqa: PLR0913
        cls,
        project_id: int,
        number: int,
        title: str | None = None,
        title_auto: bool = False,
        sections: list[Section] | None = None,
        commit: bool = True,
    ) -> Chapter:
        """
        Create a new chapter.

        Args:
            project_id: The project ID
            number: The chapter number
            title: The chapter title
            title_auto: Whether the title was auto-generated

        Keyword Args:
            sections: The sections to add to the chapter
            commit: Whether to commit the changes to the database

        Returns:
            The new :class:`~oeapp.models.chapter.Chapter` object

        """
        session = cls._get_session()
        chapter = cls(
            project_id=project_id,
            number=number,
            title=title,
            title_auto=title_auto,
        )
        if sections:
            chapter.sections = sections
        session.add(chapter)
        if commit:
            session.commit()
        else:
            session.flush()
        session.refresh(chapter)
        return chapter

    @classmethod
    def list(cls, project_id: int | None = None) -> Sequence[Chapter]:
        """
        Get all chapters.  If ``project_id`` is provided, return chapters in the
        project.

        Keyword Args:
            project_id: Project ID to filter by, if not provided, return all chapters

        Returns:
            List of :class:`~oeapp.models.chapter.Chapter` objects

        """
        session = cls._get_session()
        if project_id:
            stmt = select(cls).where(cls.project_id == project_id)
        else:
            stmt = select(cls)
        return session.scalars(stmt.order_by(cls.number)).all()

    @classmethod
    def get_chapters_after(
        cls, project_id: int, number: int, exclude_chapter_id: int | None = None
    ) -> Sequence[Chapter]:
        """
        Get the subsequent chapters by project ID and number.

        Args:
            project_id: Project ID
            number: Chapter number

        Keyword Args:
            exclude_chapter_id: Chapter ID to exclude

        Returns:
            List of subsequent chapters

        """
        session = cls._get_session()
        if exclude_chapter_id:
            stmt = select(cls).where(
                cls.project_id == project_id,
                cls.number > number,
                cls.id != exclude_chapter_id,
            )
        else:
            stmt = select(cls).where(cls.project_id == project_id, cls.number > number)
        return session.scalars(stmt.order_by(cls.number)).all()

    @classmethod
    def previous_chapter(cls, project_id: int, number: int) -> Chapter | None:
        """
        Get the chapter with the given number - 1 in the same project.

        Args:
            project_id: Project ID
            number: Chapter number

        Returns:
            The previous chapter or None if not found

        Raises:
            ValueError: If the project ID is not found

        """
        session = cls._get_session()
        return session.scalar(
            select(cls)
            .where(cls.project_id == project_id, cls.number == number - 1)
            .order_by(cls.number.desc())
            .limit(1)
        )

    def last_section_number(self) -> int:
        """
        Get the last section number in the chapter (1-based).

        Returns:
            The last section number in the project (1-based)

        """
        # Import here to avoid circular import
        from oeapp.models.section import Section  # noqa: PLC0415

        session = self._get_session()
        return (
            session.scalar(
                select(func.max(Section.number)).where(Section.chapter_id == self.id)
            )
            or 0
        )

    @property
    def display_title(self) -> str:
        """
        Get the display title for the chapter.

        Returns:
            The computed value.

        """
        if self.title:
            return self.title
        return f"Chapter {self.number}"

    def to_json(self) -> dict:
        """
        Serialize chapter to JSON-compatible dictionary (without PKs).

        Returns:
            Dictionary containing chapter data

        """
        return {
            "number": self.number,
            "title": self.title,
            "title_auto": self.title_auto,
            "sections": [
                section.to_json()
                for section in sorted(self.sections, key=lambda s: s.number)
            ],
        }

    @classmethod
    def from_json(
        cls,
        project_id: int,
        chapter_data: dict,
        commit: bool = True,
    ) -> Chapter:
        """
        Create chapter (and nested sections/paragraphs) from JSON import data.

        Args:
            project_id: Project ID
            chapter_data: Chapter data dictionary from JSON

        Keyword Args:
            commit: Whether to commit changes

        Returns:
            Created chapter

        """
        # Import here to avoid circular import
        from oeapp.models.section import Section  # noqa: PLC0415

        session = cls._get_session()
        chapter = cls(
            project_id=project_id,
            number=chapter_data["number"],
            title=chapter_data.get("title"),
            title_auto=bool(chapter_data.get("title_auto", False)),
        )
        session.add(chapter)
        session.flush()

        for section_data in chapter_data.get("sections", []):
            Section.from_json(chapter.id, section_data, commit=False)

        if commit:
            session.commit()

        return chapter
