"""Section model."""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, ForeignKey, Index, Integer, String, select
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from oeapp.db import Base
from oeapp.models.mixins import SaveDeleteMixin

if TYPE_CHECKING:
    from collections.abc import Sequence

    from oeapp.models.chapter import Chapter
    from oeapp.models.paragraph import Paragraph


class Section(SaveDeleteMixin, Base):
    """
    Represents a section within a chapter.
    """

    #: Tablename  .
    __tablename__ = "sections"
    #: Table args  .
    __table_args__ = (
        Index("idx_sections_chapter_number", "chapter_id", "number"),
    )

    #: The section ID.
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    #: The chapter ID.
    chapter_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("chapters.id", ondelete="CASCADE"), nullable=False
    )
    #: The section number (1-based).
    number: Mapped[int] = mapped_column(Integer, nullable=False)
    #: The section title.
    title: Mapped[str | None] = mapped_column(String, nullable=True)
    #: Whether section title was auto-generated by ingest logic.
    title_auto: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    #: Relationships
    chapter: Mapped[Chapter] = relationship("Chapter", back_populates="sections")
    #: Paragraphs.
    paragraphs: Mapped[builtins.list[Paragraph]] = relationship(
        "Paragraph",
        back_populates="section",
        cascade="all, delete-orphan",
        order_by="Paragraph.order",
    )

    @classmethod
    def get(cls, section_id: int) -> Section | None:
        """
        Get a section by ID.

        Args:
            section_id: Section id.

        Returns:
            The computed value.

        """
        session = cls._get_session()
        return session.get(cls, section_id)

    @classmethod
    def create(  # noqa: PLR0913
        cls,
        chapter_id: int,
        number: int,
        title: str | None = None,
        title_auto: bool = False,
        paragraphs: list[Paragraph] | None = None,
        commit: bool = True,
    ) -> Section:
        """
        Create a new section.

        Args:
            chapter_id: The chapter ID
            number: The section number
            title: The section title
            title_auto: Whether the title was auto-generated

        Keyword Args:
            paragraphs: The paragraphs to add to the section
            commit: Whether to commit the changes to the database

        Returns:
            The new :class:`~oeapp.models.section.Section` object

        """
        session = cls._get_session()
        section = cls(
            chapter_id=chapter_id,
            number=number,
            title=title,
            title_auto=title_auto,
        )
        if paragraphs:
            section.paragraphs = paragraphs
        session.add(section)
        if commit:
            session.commit()
        else:
            session.flush()
        session.refresh(section)
        return section

    @classmethod
    def list(cls, chapter_id: int | None = None) -> Sequence[Section]:
        """
        Get all sections.  If ``chapter_id`` is provided, return sections in the
        chapter.

        Args:
            chapter_id: Chapter ID

        Returns:
            List of sections ordered by (Chapter.number, Section.number)

        """
        session = cls._get_session()
        if chapter_id:
            stmt = select(cls).where(cls.chapter_id == chapter_id).order_by(cls.number)
        else:
            stmt = select(cls).order_by(cls.chapter_id, cls.number)
        return session.scalars(stmt).all()

    @classmethod
    def get_sections_after(
        cls, chapter_id: int, number: int, exclude_section_id: int | None = None
    ) -> Sequence[Section]:
        """
        Get the subsequent sections by chapter ID and number.

        Args:
            chapter_id: Chapter ID
            number: Section number

        Keyword Args:
            exclude_section_id: Section ID to exclude

        Returns:
            List of subsequent sections

        """
        session = cls._get_session()
        if exclude_section_id:
            stmt = select(cls).where(
                cls.chapter_id == chapter_id,
                cls.number > number,
                cls.id != exclude_section_id,
            )
        else:
            stmt = select(cls).where(cls.chapter_id == chapter_id, cls.number > number)
        return session.scalars(stmt.order_by(cls.number)).all()

    @classmethod
    def previous_section(cls, chapter_id: int, number: int) -> Section | None:
        """
        Get the section with the given number - 1 in the same chapter.

        Args:
            chapter_id: Chapter ID
            number: Section number

        Returns:
            The previous section or None if not found

        """
        session = cls._get_session()
        return session.scalar(
            select(cls)
            .where(cls.chapter_id == chapter_id, cls.number == number - 1)
            .order_by(cls.number.desc())
            .limit(1)
        )

    def last_paragraph_number(self) -> int:
        """
        Get the last paragraph number in the section (1-based).

        Returns:
            The computed value.

        """
        # Import here to avoid circular import
        from oeapp.models.paragraph import Paragraph  # noqa: PLC0415

        session = self._get_session()
        return (
            session.scalar(
                select(func.max(Paragraph.order)).where(Paragraph.section_id == self.id)
            )
            or 0
        )

    def get_paragraphs_after(
        self, order: int, exclude_paragraph_id: int | None = None
    ) -> Sequence[Paragraph]:
        """
        Get all paragraphs in the section, with ``order``
        greater than the given order, excluding the given paragraph ID

        Args:
            order: Paragraph order

        Keyword Args:
            exclude_paragraph_id: Paragraph ID to exclude

        Returns:
            List of subsequent paragraphs

        """
        # Import here to avoid circular import
        from oeapp.models.paragraph import Paragraph  # noqa: PLC0415

        session = self._get_session()
        if exclude_paragraph_id:
            stmt = select(Paragraph).where(
                Paragraph.section_id == self.id,
                Paragraph.order > order,
                Paragraph.id != exclude_paragraph_id,
            )
        else:
            stmt = select(Paragraph).where(
                Paragraph.section_id == self.id, Paragraph.order > order
            )
        return builtins.list(session.scalars(stmt.order_by(Paragraph.order)).all())

    @property
    def display_title(self) -> str:
        """
        Get the display title for the section.

        Returns:
            The computed value.

        """
        if self.title:
            return self.title
        return f"Section {self.number}"

    def to_json(self) -> dict:
        """
        Serialize section to JSON-compatible dictionary (without PKs).

        Returns:
            Dictionary containing section data

        """
        return {
            "number": self.number,
            "title": self.title,
            "title_auto": self.title_auto,
            "paragraphs": [
                paragraph.to_json()
                for paragraph in sorted(self.paragraphs, key=lambda p: p.order)
            ],
        }

    @classmethod
    def from_json(
        cls,
        chapter_id: int,
        section_data: dict,
        commit: bool = True,
    ) -> Section:
        """
        Create section (and nested paragraphs) from JSON import data.

        Args:
            chapter_id: Chapter ID
            section_data: Section data dictionary from JSON

        Keyword Args:
            commit: Whether to commit changes

        Returns:
            Created section

        """
        # Import here to avoid circular import
        from oeapp.models.paragraph import Paragraph  # noqa: PLC0415

        session = cls._get_session()
        section = cls(
            chapter_id=chapter_id,
            number=section_data["number"],
            title=section_data.get("title"),
            title_auto=bool(section_data.get("title_auto", False)),
        )
        session.add(section)
        session.flush()

        for paragraph_data in section_data.get("paragraphs", []):
            Paragraph.from_json(section.id, paragraph_data, commit=False)

        if commit:
            session.commit()

        return section
