"""
paragraphs

Revision ID: 0d9ebcdd2591
Revises: fix_check_constraints
Create Date: 2025-12-03 21:05:48.046540

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = "0d9ebcdd2591"
down_revision: str | Sequence[str] | None = "fix_check_constraints"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes only if they exist (they may not exist in all databases)
    connection = op.get_bind()
    inspector = inspect(connection)
    indexes = [idx["name"] for idx in inspector.get_indexes("annotations")]

    with op.batch_alter_table("annotations", schema=None) as batch_op:
        if "idx_annotations_pos" in indexes:
            batch_op.drop_index(batch_op.f("idx_annotations_pos"))
        if "idx_annotations_uncertain" in indexes:
            batch_op.drop_index(batch_op.f("idx_annotations_uncertain"))

    # Check which columns already exist
    connection = op.get_bind()
    inspector = inspect(connection)
    existing_columns = [col["name"] for col in inspector.get_columns("sentences")]

    # Add columns as nullable first (only if they don't exist)
    with op.batch_alter_table("sentences", schema=None) as batch_op:
        if "paragraph_number" not in existing_columns:
            batch_op.add_column(sa.Column("paragraph_number", sa.Integer(), nullable=True))
        if "sentence_number_in_paragraph" not in existing_columns:
            batch_op.add_column(sa.Column("sentence_number_in_paragraph", sa.Integer(), nullable=True))
        if "is_paragraph_start" not in existing_columns:
            batch_op.add_column(sa.Column("is_paragraph_start", sa.Boolean(), nullable=True))

    # Populate default values for existing rows (only if columns were just added)
    # Check if any rows have NULL values in the new columns
    result_check = connection.execute(sa.text("""
        SELECT COUNT(*) as null_count
        FROM sentences
        WHERE paragraph_number IS NULL
           OR sentence_number_in_paragraph IS NULL
           OR is_paragraph_start IS NULL
    """))

    null_count = result_check.fetchone()[0]

    if null_count > 0:
        # For existing data: all sentences are in paragraph 1, numbered sequentially per project
        # First sentence of each project starts paragraph 1
        # Get all sentences ordered by project_id and display_order
        result = connection.execute(sa.text("""
            SELECT id, project_id, display_order
            FROM sentences
            ORDER BY project_id, display_order
        """))

        current_project_id = None
        sentence_counter = 0

        for row in result:
            sentence_id, project_id, display_order = row

            # Reset counter when we move to a new project
            if current_project_id != project_id:
                current_project_id = project_id
                sentence_counter = 0

            sentence_counter += 1
            is_paragraph_start = 1 if sentence_counter == 1 else 0

            connection.execute(sa.text("""
                UPDATE sentences
                SET paragraph_number = 1,
                    sentence_number_in_paragraph = :sentence_num,
                    is_paragraph_start = :is_para_start
                WHERE id = :sentence_id
            """), {
                "sentence_num": sentence_counter,
                "is_para_start": is_paragraph_start,
                "sentence_id": sentence_id
            })

        connection.commit()

    # Now make columns NOT NULL
    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.alter_column("paragraph_number", nullable=False)
        batch_op.alter_column("sentence_number_in_paragraph", nullable=False)
        batch_op.alter_column("is_paragraph_start", nullable=False)
        batch_op.create_unique_constraint("uq_sentences_paragraph_sentence", ["project_id", "paragraph_number", "sentence_number_in_paragraph"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.drop_constraint("uq_sentences_paragraph_sentence", type_="unique")
        batch_op.drop_column("is_paragraph_start")
        batch_op.drop_column("sentence_number_in_paragraph")
        batch_op.drop_column("paragraph_number")

    # Recreate indexes if they don't exist
    connection = op.get_bind()
    inspector = inspect(connection)
    indexes = [idx["name"] for idx in inspector.get_indexes("annotations")]

    with op.batch_alter_table("annotations", schema=None) as batch_op:
        if "idx_annotations_uncertain" not in indexes:
            batch_op.create_index(batch_op.f("idx_annotations_uncertain"), ["uncertain"], unique=False)
        if "idx_annotations_pos" not in indexes:
            batch_op.create_index(batch_op.f("idx_annotations_pos"), ["pos"], unique=False)

    # ### end Alembic commands ###
