"""Remove uncertain field from annotations

Revision ID: 43b79a87ea5b
Revises: 759a3770d6a3
Create Date: 2025-12-22 13:52:33.049782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b79a87ea5b'
down_revision: Union[str, Sequence[str], None] = '759a3770d6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_column('uncertain')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uncertain', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
