"""verb_direct_case_nom

Revision ID: 4fa091868838
Revises: 6b4a10f57b2a
Create Date: 2026-02-21 16:27:30.720488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


#: revision identifiers, used by Alembic.
revision: str = '4fa091868838'
#: Down revision.
down_revision: Union[str, Sequence[str], None] = '6b4a10f57b2a'
#: Branch labels.
branch_labels: Union[str, Sequence[str], None] = None
#: Depends on.
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
