"""state

Revision ID: 714b89fcf0d8
Revises: 43b79a87ea5b
Create Date: 2025-12-26 17:33:19.365914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


#: revision identifiers, used by Alembic.
revision: str = '714b89fcf0d8'
#: Down revision.
down_revision: Union[str, Sequence[str], None] = '43b79a87ea5b'
#: Branch labels.
branch_labels: Union[str, Sequence[str], None] = None
#: Depends on.
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
