"""Remove alternatives_json field from Annotation model

Revision ID: 759a3770d6a3
Revises: da898037cfff
Create Date: 2025-12-22 13:39:02.727216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759a3770d6a3'
down_revision: Union[str, Sequence[str], None] = 'da898037cfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_column('alternatives_json')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternatives_json', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
