"""pu_po_declension

Revision ID: b4241a8588cc
Revises: 82e96253177f
Create Date: 2026-01-12 15:57:46.796761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


#: revision identifiers, used by Alembic.
revision: str = 'b4241a8588cc'
#: Down revision.
down_revision: Union[str, Sequence[str], None] = '82e96253177f'
#: Branch labels.
branch_labels: Union[str, Sequence[str], None] = None
#: Depends on.
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
