"""verb_direct_object

Revision ID: da1c8ae30409
Revises: 971ea6a048f6
Create Date: 2026-01-30 20:51:35.877764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1c8ae30409'
down_revision: Union[str, Sequence[str], None] = '971ea6a048f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verb_direct_object_case', sa.String(), nullable=True))

    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verb_direct_object_case', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_column('verb_direct_object_case')

    with op.batch_alter_table('annotation_presets', schema=None) as batch_op:
        batch_op.drop_column('verb_direct_object_case')

    # ### end Alembic commands ###
