"""
Add annotation presets table

Revision ID: da898037cfff
Revises: merge_hyphenated_words
Create Date: 2025-12-11 20:48:03.988051

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da898037cfff"
down_revision: str | Sequence[str] | None = "merge_hyphenated_words"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("annotation_presets",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("pos", sa.String(), nullable=False),
    sa.Column("gender", sa.String(), nullable=True),
    sa.Column("number", sa.String(), nullable=True),
    sa.Column("case", sa.String(), nullable=True),
    sa.Column("declension", sa.String(), nullable=True),
    sa.Column("article_type", sa.String(), nullable=True),
    sa.Column("pronoun_type", sa.String(), nullable=True),
    sa.Column("pronoun_number", sa.String(), nullable=True),
    sa.Column("verb_class", sa.String(), nullable=True),
    sa.Column("verb_tense", sa.String(), nullable=True),
    sa.Column("verb_person", sa.String(), nullable=True),
    sa.Column("verb_mood", sa.String(), nullable=True),
    sa.Column("verb_aspect", sa.String(), nullable=True),
    sa.Column("verb_form", sa.String(), nullable=True),
    sa.Column("adjective_inflection", sa.String(), nullable=True),
    sa.Column("adjective_degree", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.CheckConstraint("pos IN ('N','V','A','R','D')", name="ck_annotation_presets_pos"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name", "pos", name="uq_annotation_presets_name_pos")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("annotation_presets")
    # ### end Alembic commands ###
